### ISSUE TITLE
Most links in README are 404 broken

### ISSUE THREAD

**Issue by David-Else** [threehams/typescript-error-guide#4]
Just starting at the top, all 404...
https://github.com/threehams/typescript-error-guide/blob/master/examples/build-up-object.ts
https://github.com/threehams/typescript-error-guide/blob/master/examples/never.ts
https://github.com/threehams/typescript-error-guide/blob/master/examples/excess-property-checking.ts

**Comment by threehams** [comment]
Hi! Apparently I wasn't watching my own repo.

How'd you find this? It's still in really early stages, and I haven't really advertised it anywhere, so there are bugs all over.

**Comment by David-Else** [comment]
I don't remember how it found it now, was ages ago! Good luck with it all.

**Comment by David-Else** [comment]
Closing for Christmas.
